version: '3.8'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: deployments/compose/django/Dockerfile
    image: django_web
    command: /start
    volumes:
      - .:/app
    ports:
      - "8007:8000"
    env_file:
      - envs/.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=djangodefault
      - POSTGRES_PASSWORD=1253
    ports:
      - "5437:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  telegram_bot:
    build:
      context: .
      dockerfile: deployments/compose/telegram_bot/Dockerfile
    command: python apps/infobot/InfoBot/main.py
    volumes:
      - .:/app
    depends_on:
      - web
    restart: on-failure

volumes:
  postgres_data: