# Generated by Django 5.0.3 on 2024-07-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApplicationInvestor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "Investorlik arizasi",
                "verbose_name_plural": "Investorlik arizalari",
            },
        ),
        migrations.CreateModel(
            name="ApplicationPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hamkorlik arizasi",
                "verbose_name_plural": "Hamkorlik arizalari",
            },
        ),
        migrations.CreateModel(
            name="BotUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("telegram_id", models.BigIntegerField(unique=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.BigIntegerField(blank=True, null=True, unique=True)),
                (
                    "language_code",
                    models.CharField(
                        choices=[
                            ("uz", "O'zbek tili"),
                            ("ru", "Rus tili"),
                            ("en", "Ingliz tili"),
                        ],
                        default="uz",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("moderator", "Moderator"),
                            ("user", "Foydalanuvchi"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot foaydalanuvchisi",
                "verbose_name_plural": "Bot foydalanuvchilari",
                "db_table": "bot_users",
            },
        ),
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("name_uz", models.CharField(max_length=200, null=True)),
                ("name_ru", models.CharField(max_length=200, null=True)),
                ("name_en", models.CharField(max_length=200, null=True)),
                ("address", models.CharField(max_length=200)),
                ("address_uz", models.CharField(max_length=200, null=True)),
                ("address_ru", models.CharField(max_length=200, null=True)),
                ("address_en", models.CharField(max_length=200, null=True)),
                ("phone", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField()),
                ("description", models.TextField()),
                ("description_uz", models.TextField(null=True)),
                ("description_ru", models.TextField(null=True)),
                ("description_en", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "Kompaniya ma'lumoti",
                "verbose_name_plural": "Kompaniya ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("name_uz", models.CharField(max_length=255, null=True)),
                ("name_ru", models.CharField(max_length=255, null=True)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("email", models.EmailField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("phone2", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True, null=True)),
                ("message_uz", models.TextField(blank=True, null=True)),
                ("message_ru", models.TextField(blank=True, null=True)),
                ("message_en", models.TextField(blank=True, null=True)),
                ("address", models.CharField(max_length=255)),
                ("address_uz", models.CharField(max_length=255, null=True)),
                ("address_ru", models.CharField(max_length=255, null=True)),
                ("address_en", models.CharField(max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Aloqa ma'lumoti",
                "verbose_name_plural": "Aloqa ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField()),
                ("question_uz", models.TextField(null=True)),
                ("question_ru", models.TextField(null=True)),
                ("question_en", models.TextField(null=True)),
                ("answer", models.TextField()),
                ("answer_uz", models.TextField(null=True)),
                ("answer_ru", models.TextField(null=True)),
                ("answer_en", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.CreateModel(
            name="Investor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("name_uz", models.CharField(max_length=255, null=True)),
                ("name_ru", models.CharField(max_length=255, null=True)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("description", models.TextField()),
                ("description_uz", models.TextField(null=True)),
                ("description_ru", models.TextField(null=True)),
                ("description_en", models.TextField(null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="investors/"),
                ),
            ],
            options={
                "verbose_name": "Investor",
                "verbose_name_plural": "Investorlar",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_uz", models.CharField(max_length=255, null=True)),
                ("title_ru", models.CharField(max_length=255, null=True)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("description", models.TextField()),
                ("description_uz", models.TextField(null=True)),
                ("description_ru", models.TextField(null=True)),
                ("description_en", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "Yangilik",
                "verbose_name_plural": "Yangiliklar",
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("name_uz", models.CharField(max_length=255, null=True)),
                ("name_ru", models.CharField(max_length=255, null=True)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("description", models.TextField()),
                ("description_uz", models.TextField(null=True)),
                ("description_ru", models.TextField(null=True)),
                ("description_en", models.TextField(null=True)),
                ("logo", models.ImageField(upload_to="partners/")),
            ],
            options={
                "verbose_name": "Hamkor",
                "verbose_name_plural": "Hamkorlar",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("name_uz", models.CharField(max_length=255, null=True)),
                ("name_ru", models.CharField(max_length=255, null=True)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("description", models.TextField()),
                ("description_uz", models.TextField(null=True)),
                ("description_ru", models.TextField(null=True)),
                ("description_en", models.TextField(null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
            ],
            options={
                "verbose_name": "Xizmat",
                "verbose_name_plural": "Xizmatlar",
            },
        ),
    ]
